apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: >-
      ClusterLogForwarder.v1.logging.openshift.io,ClusterLogging.v1.logging.openshift.io
  namespace: openshift-logging
  name: openshift-logging-twtw1
spec:
  targetNamespaces:
    - openshift-logging