kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: etcd-backup
  namespace: etcd-infra
  labels:
    app: etcd-infra
spec:
  schedule: 0 */12 * * *
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          generateName: etcd-backup-
          namespace: etcd-infra
          labels:
            app: etcd-infra
          annotations:
            openshift.io/scc: node-exporter
        spec:
          nodeSelector:
            node-role.kubernetes.io/master: ''
          restartPolicy: Never
          serviceAccountName: etcd-backup
          schedulerName: default-scheduler
          hostNetwork: true
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - resources: {}
              stdin: true
              terminationMessagePath: /dev/termination-log
              name: etcd-backup
              command:
                - /usr/bin/bash
                - '-c'
                - /tmp/backup-scripts/manage-backup
              env:
                - name: BACKUP_PATH
                  value: /tmp/etcd_backup/assets
                - name: BACKUP_SCRIPT
                  value: /usr/local/bin/cluster-backup.sh
              securityContext:
                privileged: true
                runAsUser: 0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: etcd-backup-scripts
                  readOnly: true
                  mountPath: /tmp/backup-scripts/
                - name: host
                  mountPath: /host
                - name: etcd-backup-data
                  mountPath: /tmp/etcd_backup/assets
              terminationMessagePolicy: File
              tty: true
              image: UPDATE_ME/rhel7/support-tools
          serviceAccount: etcd-backup
          volumes:
            - name: etcd-backup-scripts
              configMap:
                name: etcd-backup-scripts
                defaultMode: 511
            - name: host
              hostPath:
                path: /
                type: Directory
            - name: etcd-backup-data
              persistentVolumeClaim:
                claimName: etcd-backup
          dnsPolicy: ClusterFirst
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2