kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'cluster-manager-admin-crb'
subjects:
  # Add any groups here
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kube:admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:cluster-manager-admin'
