kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'subscription-admin-crb'
subjects:
  # Add any groups here
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kube:admin
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops 
  - kind: User
    name: system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
