kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ocp-cis-scansettingbinding.yaml
  - ocp-cis-scansetting.yaml