apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- argo-cr.yaml

patches:
-  target:
     kind: ArgoCD
     name: openshift-gitops
     namespace: openshift-gitops
   patch: |-
    - op: add
      path: /spec/rbac
      value:
        policy: |
          g, system:cluster-admins, role:admin
          g, cluster-admins, role:admin
          g, MY_CLUSTER_ADMIN_ROLE, role:admin
        scopes: "[groups]"